## eureka地址
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.10.183.67:18010/eureka

spring:
  redis:
    host: localhost
  servlet:
    # =========================== 文件上传 ===========================
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 250MB
  # =========================== zipkin ===========================
#  zipkin:
#    base-url: http://10.10.183.67:9411
#  # =========================== sleuth ===========================
#  sleuth:
#    web:
#    client:
#      enabled: true
#    sampler:
#      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
#    enabled: true
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  #url: jdbc:mysql://10.10.183.126:3306/allinone?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  url: jdbc:mysql://localhost:3306/allinone?characterEncoding=utf8&autoReconnect=true
  username: root
  password: root
rocketmq:
  producer:
    namesrvAddr: 10.10.183.76:9876
  consumer:
    namesrvAddr: 10.10.183.76:9876