

# eureka地址
eureka.client.serviceUrl.defaultZone: http://127.0.0.1:18010/eureka

spring:
  redis:
    host: 10.10.183.133
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.10.183.136:3306/fnp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  username: maap
  password: maap
rocketmq:
  producer:
    namesrvAddr: 10.10.183.76:9876
  consumer:
    namesrvAddr: 10.10.183.76:9876